name: Lint and Commit

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
  schedule:
    - cron: '44 7 * * 3'

jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install ruff
    - run:
        ruff check --fix
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        push_options: --force
        commit_message: 'style fixes by ruff'
        skip_checkout: true
        branch: development
